version: "3.8"

services:
  # Service PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - bank-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankuser -d bankdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Service Application Spring Boot
  bank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Configuration Base de données
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bankdb
      DB_USERNAME: bankuser
      DB_PASSWORD: bankpass

      # Configuration JWT
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

      # Configuration Spring
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      # Configuration JVM
      JAVA_OPTS: -Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/app/logs
    networks:
      - bank-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/auth/status",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Service pgAdmin (optionnel - pour administration de la BDD)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bank-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@banksystem.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bank-network
    depends_on:
      - postgres
    profiles:
      - admin

# Volumes pour la persistance des données
volumes:
  postgres_data:
    driver: local
    name: bank_postgres_data
  app_logs:
    driver: local
    name: bank_app_logs
  pgadmin_data:
    driver: local
    name: bank_pgadmin_data

# Réseau pour la communication entre les services
networks:
  bank-network:
    driver: bridge
    name: bank-network
